export const APARTMENTS = [
  {
    id: 1,
    name: "Sunset Apartment",
    location: "Zadar",
    category: "Apartments",
    description:
      "Modern apartment near the beach with a spacious balcony and sea view.",
    images: ["Sunset.jpg"],
    size_m2: 48,
    tags: ["near beach", "balcony", "parking", "air conditioning", "microwave"],
    price_per_night: 145,
    max_guests: 4,
    availability: "",
    rating: 4.8,
    reviews_count: 214,
  },
  {
    id: 2,
    name: "Villa Maris",
    location: "Korčula",
    category: "Houses",
    description:
      "Traditional stone villa with modern interior and outdoor dining area.",
    images: [
      "Maris1.png",
      "Maris2.png",
      "Maris3.png",
      "Maris4.png",
      "Maris5.png",
      "Maris6.png",
    ],
    size_m2: 120,
    tags: ["near beach", "parking", "balcony", "nature", "air conditioning"],
    price_per_night: 360,
    max_guests: 6,
    availability: "",
    rating: 4.9,
    reviews_count: 64,
  },
  {
    id: 3,
    name: "Hotel Adriana – Deluxe Apartment",
    location: "Hvar",
    category: "Hotels",
    description:
      "Elegant hotel apartment with access to private beach, pool and wellness facilities.",
    images: ["Adriana1.jpg", "Adriana2.jpg", "Adriana3.jpg"],
    size_m2: 50,
    tags: [
      "pool",
      "near centre",
      "near beach",
      "breakfast",
      "spa",
      "sport",
      "air conditioning",
      "elevator",
      "parking",
      "balcony",
    ],
    price_per_night: 220,
    max_guests: 2,
    availability: "",
    rating: 4.9,
    reviews_count: 126,
  },
  {
    id: 4,
    name: "Luxury Glamping Dome",
    location: "Brač",
    category: "Glamping",
    description: "Premium glamping dome with private jacuzzi and sea view.",
    images: [
      "Glamping-Dome1.jpg",
      "Glamping-Dome2.jpg",
      "Glamping-Dome3.jpg",
      "Glamping-Dome4.jpg",
    ],
    size_m2: 45,
    tags: ["nature", "near beach", "balcony", "air conditioning", "parking"],
    price_per_night: 155,
    max_guests: 3,
    availability: "",
    rating: 4.9,
    reviews_count: 289,
  },

  {
    id: 5,
    name: "Pinewood Mobile Home",
    location: "Dugi Otok",
    category: "Camping",
    description:
      "Fully equipped mobile home surrounded by pine trees, perfect for families.",
    images: ["Pinewood1.png", "Pinewood2.png"],
    size_m2: 40,
    tags: ["near beach", "parking", "nature", "air conditioning", "microwave"],
    price_per_night: 145,
    max_guests: 4,
    availability: "",
    rating: 4.6,
    reviews_count: 143,
  },

  {
    id: 6,
    name: "Stone Villa Maslina",
    location: "Vis",
    category: "Houses",
    description:
      "A rustic stone villa nestled in a private olive grove, featuring an elegant pool and a warm, luxurious interior crafted from natural materials. Blending traditional Dalmatian architecture with modern comfort, this secluded retreat offers complete privacy, Mediterranean charm, and a premium island escape for guests seeking something truly special.",
    images: [
      "Maslina1.png",
      "Maslina2.png",
      "Maslina3.png",
      "Maslina4.png",
      "Maslina5.png",
    ],
    size_m2: 132,
    tags: [
      "pool",
      "nature",
      "air conditioning",
      "parking",
      "washer",
      "sport",
      "pets allowed",
    ],
    price_per_night: 320,
    max_guests: 6,
    availability: "",
    rating: 4.8,
    reviews_count: 52,
  },

  {
    id: 7,
    name: "Lavender Holiday House",
    location: "Mljet",
    category: "Houses",
    description: "Spacious holiday home with garden and outdoor grill.",
    images: ["lavander1.png", "lavander2.png", "lavander3.png"],
    size_m2: 80,
    tags: [
      "pool",
      "parking",
      "air conditioning",
      "washer",
      "dishwasher",
      "microwave",
      "balcony",
    ],
    price_per_night: 130,
    max_guests: 5,
    availability: "",
    rating: 4.8,
    reviews_count: 233,
  },

  {
    id: 8,
    name: "Forest Glamping Krk",
    location: "Krk",
    category: "Glamping",
    description:
      "Modern glamping tent with a kitchen, private beach, pool, and direct access to untouched nature. Surrounded by pine trees and coastal trails, this unique stay offers a peaceful outdoor escape with plenty of sports opportunities, including kayaking, hiking, snorkeling, and stand‑up paddling.",
    images: ["Krk1.jpg", "Krk2.jpg", "Krk3.jpg"],
    size_m2: 30,
    tags: ["pool", "nature", "air conditioning", "microwave", "parking"],
    price_per_night: 120,
    max_guests: 3,
    availability: "",
    rating: 4.7,
    reviews_count: 139,
  },
  {
    id: 9,
    name: "Greenstar Holiday Home",
    location: "Rogoznica",
    category: "Houses",
    description:
      "Charming and modern holiday home with a private terrace, pool and outdoor dining area surrounded by peaceful nature.",
    images: [
      "rogoznica1.png",
      "rogoznica2.png",
      "rogoznica3.png",
      "rogoznica4.png",
    ],
    size_m2: 72,
    tags: [
      "pool",
      "near beach",
      "parking",
      "air conditioning",
      "washer",
      "microwave",
    ],
    price_per_night: 240,
    max_guests: 5,
    availability: "",
    rating: 4.7,
    reviews_count: 189,
  },

  {
    id: 10,
    name: "Oldtown Apartment",
    location: "Šibenik",
    category: "Apartments",
    description:
      "Bright apartment in the medieval town centre, combining traditional rustical furniture with modern facilities.",
    images: ["sibenik1.jpg", "sibenik2.jpg", "sibenik3.jpg", "sibenik4.jpg"],
    size_m2: 55,
    tags: [
      "near centre",
      "air conditioning",
      "microwave",
      "balcony",
      "parking",
    ],
    price_per_night: 120,
    max_guests: 4,
    availability: "",
    rating: 4.7,
    reviews_count: 158,
  },
  {
    id: 11,
    name: "Cozy Studio Trogir",
    location: "Trogir",
    category: "Studio",
    description:
      "Small but stylish studio located in the heart of the old town, with beatuful view.",
    images: ["trogir1.jpg", "trogir2.jpg", "trogir3.jpg"],
    size_m2: 24,
    tags: ["near centre", "air conditioning", "microwave", "balcony"],
    price_per_night: 135,
    max_guests: 2,
    availability: "",
    rating: 4.4,
    reviews_count: 49,
  },

  {
    id: 12,
    name: "Hotel Bellevue – Premium Apartment",
    location: "Dubrovnik",
    category: "Hotels",
    description:
      "Luxury hotel apartment with rooftop pool, sea view and premium amenities.",
    images: [
      "Bellevue1.jpg",
      "Bellevue2.jpg",
      "Bellevue3.jpg",
      "Bellevue4.jpg",
    ],
    size_m2: 28,
    tags: [
      "pool",
      "balcony",
      "near beach",
      "near centre",
      "breakfast",
      "air conditioning",
      "elevator",
      "parking",
      "spa",
      "sport",
      "nature",
    ],
    price_per_night: 410,
    max_guests: 2,
    availability: "",
    rating: 4.9,
    reviews_count: 312,
  },

  {
    id: 13,
    name: "Beachfront Rooms Coral",
    location: "Baška",
    category: "Hotels",
    description:
      "Room just steps from the beach, perfect for a relaxing getaway.",
    images: [],
    size_m2: 20,
    tags: [
      "near beach",
      "balcony",
      "air conditioning",
      "elevator",
      "breakfast",
      "parking",
    ],
    price_per_night: 150,
    max_guests: 2,
    availability: "",
    rating: 4.5,
    reviews_count: 112,
  },
  {
    id: 14,
    name: "Family Mobile Home Breeze",
    location: "Biograd na Moru",
    category: "Camping",
    description: "Modern mobile home with two bedrooms and a large terrace.",
    images: [],
    size_m2: 42,
    tags: ["near beach", "parking", "air conditioning", "nature", "microwave"],
    price_per_night: 110,
    max_guests: 5,
    availability: "",
    rating: 4.6,
    reviews_count: 167,
  },

  {
    id: 15,
    name: "Azure Apartment",
    location: "Omiš",
    category: "Apartments",
    description: "Stylish apartment with mountain and sea views.",
    images: [],
    size_m2: 50,
    tags: ["near beach", "air conditioning", "parking", "balcony", "microwave"],
    price_per_night: 105,
    max_guests: 4,
    availability: "",
    rating: 4.6,
    reviews_count: 152,
  },
  {
    id: 16,
    name: "Minimalist Studio Port",
    location: "Rijeka",
    category: "Studio",
    description: "Modern studio close to the port and city attractions.",
    images: [],
    size_m2: 27,
    tags: ["near centre", "air conditioning", "microwave"],
    price_per_night: 95,
    max_guests: 2,
    availability: "",
    rating: 4.3,
    reviews_count: 61,
  },
  {
    id: 17,
    name: "Olive Grove Holiday Home",
    location: "Pag",
    category: "Houses",
    description: "Charming stone house surrounded by olive trees.",
    images: [],
    size_m2: 68,
    tags: [
      "parking",
      "air conditioning",
      "washer",
      "microwave",
      "nature",
      "pets allowed",
    ],
    price_per_night: 145,
    max_guests: 5,
    availability: "",
    rating: 4.7,
    reviews_count: 174,
  },
  {
    id: 18,
    name: "City Rooms Panorama",
    location: "Zadar",
    category: "Hotels",
    description: "Room with panoramic city views, ideal for short stays.",
    images: [],
    size_m2: 18,
    tags: [
      "near centre",
      "air conditioning",
      "elevator",
      "breakfast",
      "parking",
    ],
    price_per_night: 135,
    max_guests: 2,
    availability: "",
    rating: 4.4,
    reviews_count: 48,
  },
  {
    id: 19,
    name: "Seabreeze Mobile Home",
    location: "Umag",
    category: "Camping",
    description: "Comfortable mobile home located in a quiet coastal area.",
    images: [],
    size_m2: 38,
    tags: ["near beach", "parking", "air conditioning", "nature", "microwave"],
    price_per_night: 90,
    max_guests: 4,
    availability: "",
    rating: 4.5,
    reviews_count: 131,
  },
  {
    id: 20,
    name: "Seaside Rooms",
    location: "Makarska",
    category: "Hotels",
    description: "Comfortable private room with balcony and partial sea view.",
    images: [],
    size_m2: 22,
    tags: [
      "near beach",
      "balcony",
      "parking",
      "air conditioning",
      "elevator",
      "breakfast",
    ],
    price_per_night: 150,
    max_guests: 2,
    availability: "",
    rating: 4.3,
    reviews_count: 54,
  },

  {
    id: 21,
    name: "Hillside Family House",
    location: "Opatija",
    category: "Houses",
    description:
      "Comfortable family house with a private garden and sea-view terrace.",
    images: ["Hillside1.jpg"],
    size_m2: 76,
    tags: ["parking", "balcony", "air conditioning", "washer", "near centre"],
    price_per_night: 170,
    max_guests: 5,
    availability: "",
    rating: 4.7,
    reviews_count: 162,
  },
  {
    id: 22,
    name: "Blue Studio Retreat",
    location: "Vodice",
    category: "Studio",
    description:
      "Cozy studio ideal for couples, located close to the city center, harbor and beach, with beautiful view from the balcony.",
    images: ["vodice1.jpg", "vodice2.jpg", "vodice3.jpg", "vodice4.jpg"],
    size_m2: 28,
    tags: ["near centre", "air conditioning", "microwave"],
    price_per_night: 130,
    max_guests: 2,
    availability: "",
    rating: 4.7,
    reviews_count: 167,
  },

  {
    id: 23,
    name: "Rustic Countryside House",
    location: "Pelješac",
    category: "Houses",
    description:
      "Peaceful countryside retreat surrounded by vineyards and olive groves near the sea.",
    images: [],
    size_m2: 70,
    tags: ["nature", "parking", "washer", "pets allowed"],
    price_per_night: 165,
    max_guests: 4,
    availability: "",
    rating: 4.6,
    reviews_count: 118,
  },
  {
    id: 24,
    name: "Seaview Holiday Cottage",
    location: "Rab",
    category: "Houses",
    description:
      "Charming cottage with panoramic sea views and a private terrace.",
    images: ["Cottage1.jpg"],
    size_m2: 60,
    tags: ["near beach", "balcony", "parking", "air conditioning"],
    price_per_night: 125,
    max_guests: 4,
    availability: "",
    rating: 4.8,
    reviews_count: 176,
  },

  {
    id: 25,
    name: "Urban Studio Loft",
    location: "Zadar",
    category: "Studio",
    description:
      "Modern loft-style studio close to the old town and waterfront.",
    images: ["Loft1.jpg"],
    size_m2: 30,
    tags: ["near centre", "air conditioning", "microwave"],
    price_per_night: 125,
    max_guests: 2,
    availability: "",
    rating: 4.5,
    reviews_count: 88,
  },
  {
    id: 26,
    name: "Harbor View Studio",
    location: "Rijeka",
    category: "Studio",
    description: "Compact studio with a beautiful view of the harbor.",
    images: [],
    size_m2: 26,
    tags: ["near centre", "air conditioning"],
    price_per_night: 89,
    max_guests: 2,
    availability: "",
    rating: 4.4,
    reviews_count: 73,
  },
  {
    id: 27,
    name: "Old Town Mini Studio",
    location: "Rab",
    category: "Studio",
    description:
      "Small but charming studio located in a historic stone building near the sea.",
    images: ["MiniStudio1.jpg"],
    size_m2: 22,
    tags: ["near centre", "air conditioning"],
    price_per_night: 60,
    max_guests: 2,
    availability: "",
    rating: 4.3,
    reviews_count: 59,
  },

  {
    id: 28,
    name: "Harborfront Apartment",
    location: "Rovinj",
    category: "Apartments",
    description:
      "Bright apartment overlooking the old harbor, ideal for couples.",
    images: ["Harborfront1.jpg"],
    size_m2: 52,
    tags: ["near centre", "air conditioning", "balcony"],
    price_per_night: 115,
    max_guests: 3,
    availability: "",
    rating: 4.8,
    reviews_count: 190,
  },
  {
    id: 29,
    name: "Garden View Apartment",
    location: "Pula",
    category: "Apartments",
    description:
      "Quiet apartment with a relaxing garden view and private patio.",
    images: [],
    size_m2: 47,
    tags: ["parking", "air conditioning", "microwave"],
    price_per_night: 90,
    max_guests: 4,
    availability: "",
    rating: 4.6,
    reviews_count: 121,
  },
  {
    id: 30,
    name: "Old Town Comfort Apartment",
    location: "Poreč",
    category: "Apartments",
    description:
      "Comfortable apartment located in the old town, close to the waterfront.",
    images: ["CityCenter1.jpg"],
    size_m2: 58,
    tags: ["near centre", "air conditioning", "washer"],
    price_per_night: 110,
    max_guests: 4,
    availability: "",
    rating: 4.7,
    reviews_count: 210,
  },
  {
    id: 31,
    name: "Beachline Apartment",
    location: "Makarska",
    category: "Apartments",
    description: "Modern beachfront apartment with a large balcony.",
    images: ["Beachline1.jpg", "Beachline2.jpg"],
    size_m2: 54,
    tags: ["near beach", "balcony", "air conditioning", "parking"],
    price_per_night: 130,
    max_guests: 4,
    availability: "",
    rating: 4.9,
    reviews_count: 244,
  },
  {
    id: 32,
    name: "Mountain View Apartment",
    location: "Senj",
    category: "Apartments",
    description:
      "Cozy apartment with sea and mountain views above the coastline.",
    images: [],
    size_m2: 45,
    tags: ["nature", "parking", "air conditioning"],
    price_per_night: 85,
    max_guests: 3,
    availability: "",
    rating: 4.5,
    reviews_count: 97,
  },

  {
    id: 33,
    name: "Hotel Riviera – Superior Room",
    location: "Pula",
    category: "Hotels",
    description: "Spacious superior room with modern amenities and city views.",
    // images: ["http://localhost:5000/images/Riviera1.png", "http://localhost:5000/images/Riviera2.png"],
    images: ["Riviera1.png", "Riviera2.png"],
    size_m2: 32,
    tags: [
      "near centre",
      "breakfast",
      "air conditioning",
      "elevator",
      "parking",
      "spa",
    ],
    price_per_night: 175,
    max_guests: 3,
    availability: "",
    rating: 4.8,
    reviews_count: 221,
  },

  {
    id: 34,
    name: "Hotel Central – Superior Room",
    location: "Split",
    category: "Hotels",
    description:
      "Comfortable superior room located near the old town and promenade.",
    images: [],
    size_m2: 24,
    tags: ["near centre", "breakfast", "air conditioning", "elevator"],
    price_per_night: 125,
    max_guests: 2,
    availability: "",
    rating: 4.4,
    reviews_count: 178,
  },

  {
    id: 35,
    name: "Lakeside Mobile Home",
    location: "Pakoštane",
    category: "Camping",
    description: "Modern mobile home near the sea and coastal pine forest.",
    images: ["Lakeside1.jpg"],
    size_m2: 38,
    tags: ["nature", "parking", "air conditioning", "near beach"],
    price_per_night: 95,
    max_guests: 4,
    availability: "",
    rating: 4.7,
    reviews_count: 156,
  },

  {
    id: 6,
    name: "Glamping Oasis",
    location: "Mali Lošinj",
    category: "Glamping",
    description:
      "Eco-friendly glamping tent with private beach, surrounded by Mediterranean forest.",
    images: ["Oasis1.jpg", "Oasis2.jpg", "Oasis3.jpg"],
    size_m2: 35,
    tags: ["nature", "near beach", "air conditioning", "balcony", "parking"],
    price_per_night: 110,
    max_guests: 3,
    availability: "",
    rating: 4.8,
    reviews_count: 201,
  },

  {
    id: 37,
    name: "Cliffside Panorama Apartment",
    location: "Dubrovnik",
    category: "Apartments",
    description:
      "Modern apartment perched above the cliffs with breathtaking panoramic sea views.",
    images: ["Cliffside1.jpg", "Cliffside2.jpg"],
    size_m2: 53,
    tags: ["near beach", "balcony", "air conditioning", "parking"],
    price_per_night: 145,
    max_guests: 3,
    availability: "",
    rating: 4.8,
    reviews_count: 187,
  },
];
