export const APARTMENTS = [
  {
    "id": 1,
    "name": "Sunset Apartment",
    "location": "Zadar",
    "category": "Apartments",
    "description": "Modern apartment near the beach with a spacious balcony and sea view.",
    "images": ["http://localhost:5000/images/Sunset.jpg"],
    "size_m2": 48,
    "tags": ["near beach", "sea view", "parking"],
    "price_per_night": 95,
    "max_guests": 4,
    "availability": "",
    "rating": 4.8,
    "reviews_count": 214
  },
  {
    "id": 2,
    "name": "Blue Studio Retreat",
    "location": "Split",
    "category": "Studio",
    "description": "Cozy studio ideal for couples, located close to the city center.",
    "images": [],
    "size_m2": 28,
    "tags": ["near center", "wifi"],
    "price_per_night": 70,
    "max_guests": 2,
    "availability": "",
    "rating": 4.4,
    "reviews_count": 67
  },
  {
    "id": 3,
    "name": "Adriatic Holiday Home",
    "location": "Rogoznica",
    "category": "Houses",
    "description": "Charming holiday home with a private terrace and outdoor dining area.",
    "images": [],
    "size_m2": 72,
    "tags": ["near beach", "parking", "family friendly"],
    "price_per_night": 120,
    "max_guests": 5,
    "availability": "",
    "rating": 4.7,
    "reviews_count": 189
  },
  {
    "id": 4,
    "name": "Seaside Rooms",
    "location": "Makarska",
    "category": "Hotels",
    "description": "Comfortable private room with balcony and partial sea view.",
    "images": [],
    "size_m2": 22,
    "tags": ["near beach", "balcony"],
    "price_per_night": 60,
    "max_guests": 2,
    "availability": "",
    "rating": 4.3,
    "reviews_count": 54
  },
  {
    "id": 5,
    "name": "Pinewood Mobile Home",
    "location": "Poreč",
    "category": "Camping",
    "description": "Fully equipped mobile home surrounded by pine trees, perfect for families.",
    "images": [],
    "size_m2": 40,
    "tags": ["near beach", "parking", "terrace"],
    "price_per_night": 85,
    "max_guests": 4,
    "availability": "",
    "rating": 4.6,
    "reviews_count": 143
  },
  {
    "id": 6,
    "name": "Glamping Oasis",
    "location": "Krk",
    "category": "Glamping",
    "description": "Luxury glamping tent with private deck and nature views.",
    "images": [],
    "size_m2": 35,
    "tags": ["nature", "near beach", "wifi"],
    "price_per_night": 110,
    "max_guests": 3,
    "availability": "",
    "rating": 4.8,
    "reviews_count": 201
  },
  {
    "id": 7,
    "name": "Hotel Adriana – Double Room",
    "location": "Hvar",
    "category": "Hotels",
    "description": "Elegant hotel room with access to pool and wellness facilities.",
   "images": ["http://localhost:5000/images/Adriana1.jpg"],
    "size_m2": 30,
    "tags": ["pool", "near center", "breakfast included"],
    "price_per_night": 140,
    "max_guests": 2,
    "availability": "",
    "rating": 4.9,
    "reviews_count": 276
  },
  {
    "id": 8,
    "name": "Marina View Apartment",
    "location": "Trogir",
    "category": "Apartments",
    "description": "Bright apartment overlooking the marina, ideal for longer stays.",
    "images": [],
    "size_m2": 55,
    "tags": ["sea view", "near center", "wifi"],
    "price_per_night": 100,
    "max_guests": 4,
    "availability": "",
    "rating": 4.7,
    "reviews_count": 158
  },
  {
    "id": 9,
    "name": "Cozy Studio Old Town",
    "location": "Šibenik",
    "category": "Studio",
    "description": "Small but stylish studio located in the heart of the old town.",
    "images": [],
    "size_m2": 24,
    "tags": ["near center", "historic area"],
    "price_per_night": 65,
    "max_guests": 2,
    "availability": "",
    "rating": 4.4,
    "reviews_count": 49
  },
  {
    "id": 10,
    "name": "Lavender Holiday House",
    "location": "Vodice",
    "category": "Houses",
    "description": "Spacious holiday home with garden and outdoor grill.",
    "images": [],
    "size_m2": 80,
    "tags": ["garden", "parking", "family friendly"],
    "price_per_night": 130,
    "max_guests": 5,
    "availability": "",
    "rating": 4.8,
    "reviews_count": 233
  },
  {
    "id": 11,
    "name": "Beachfront Rooms Coral",
    "location": "Baška",
    "category": "Hotels",
    "description": "Room just steps from the beach, perfect for a relaxing getaway.",
    "images": [],
    "size_m2": 20,
    "tags": ["near beach", "balcony"],
    "price_per_night": 75,
    "max_guests": 2,
    "availability": "",
    "rating": 4.5,
    "reviews_count": 112
  },
  {
    "id": 12,
    "name": "Family Mobile Home Breeze",
    "location": "Biograd na Moru",
    "category": "Camping",
    "description": "Modern mobile home with two bedrooms and a large terrace.",
    "images": [],
    "size_m2": 42,
    "tags": ["near beach", "parking", "family friendly"],
    "price_per_night": 90,
    "max_guests": 5,
    "availability": "",
    "rating": 4.6,
    "reviews_count": 167
  },
  {
    "id": 13,
    "name": "Forest Glamping Pod",
    "location": "Lošinj",
    "category": "Glamping",
    "description": "Eco-friendly glamping pod surrounded by Mediterranean forest.",
    "images": [],
    "size_m2": 30,
    "tags": ["nature", "quiet area"],
    "price_per_night": 95,
    "max_guests": 3,
    "availability": "",
    "rating": 4.7,
    "reviews_count": 139
  },
  {
    "id": 14,
    "name": "Hotel Riviera – Superior Room",
    "location": "Pula",
    "category": "Hotels",
    "description": "Spacious superior room with modern amenities and city views.",
    "images": [],
    "size_m2": 32,
    "tags": ["near center", "breakfast included"],
    "price_per_night": 125,
    "max_guests": 3,
    "availability": "",
    "rating": 4.8,
    "reviews_count": 221
  },
  {
    "id": 15,
    "name": "Azure Apartment",
    "location": "Omiš",
    "category": "Apartments",
    "description": "Stylish apartment with mountain and sea views.",
    "images": [],
    "size_m2": 50,
    "tags": ["sea view", "near beach"],
    "price_per_night": 105,
    "max_guests": 4,
    "availability": "",
    "rating": 4.6,
    "reviews_count": 152
  },
  {
    "id": 16,
    "name": "Minimalist Studio Port",
    "location": "Rijeka",
    "category": "Studio",
    "description": "Modern studio close to the port and city attractions.",
    "images": [],
    "size_m2": 27,
    "tags": ["near center", "wifi"],
    "price_per_night": 68,
    "max_guests": 2,
    "availability": "",
    "rating": 4.3,
    "reviews_count": 61
  },
  {
    "id": 17,
    "name": "Olive Grove Holiday Home",
    "location": "Pag",
    "category": "Houses",
    "description": "Charming stone house surrounded by olive trees.",
    "images": [],
    "size_m2": 68,
    "tags": ["quiet area", "parking", "garden"],
    "price_per_night": 115,
    "max_guests": 5,
    "availability": "",
    "rating": 4.7,
    "reviews_count": 174
  },
  {
    "id": 18,
    "name": "City Rooms Panorama",
    "location": "Zadar",
    "category": "Hotels",
    "description": "Room with panoramic city views, ideal for short stays.",
    "images": [],
    "size_m2": 18,
    "tags": ["near center", "wifi"],
    "price_per_night": 55,
    "max_guests": 2,
    "availability": "",
    "rating": 4.4,
    "reviews_count": 48
  },
  {
    "id": 19,
    "name": "Seabreeze Mobile Home",
    "location": "Umag",
    "category": "Camping",
    "description": "Comfortable mobile home located in a quiet coastal area.",
    "images": [],
    "size_m2": 38,
    "tags": ["near beach", "parking"],
    "price_per_night": 80,
    "max_guests": 4,
    "availability": "",
    "rating": 4.5,
    "reviews_count": 131
  },
  {
    "id": 20,
    "name": "Luxury Glamping Dome",
    "location": "Brač",
    "category": "Glamping",
    "description": "Premium glamping dome with private jacuzzi and sea view.",
    "images": ["http://localhost:5000/images/Glamping-Dome.jpg"],
    "size_m2": 45,
    "tags": ["jacuzzi", "sea view", "luxury"],
    "price_per_night": 150,
    "max_guests": 3,
    "availability": "",
    "rating": 4.9,
    "reviews_count": 289
  }
]
